<?php

namespace udecBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * telefonoEstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class telefonoEstudianteRepository extends EntityRepository
{
}
